application: website
version: 1
runtime: go
api_version: go1

handlers:
- url: /api/location/new
  script: _go_app
  login: admin
- url: /api/location
  script: _go_app
- url: /api/music/new
  script: _go_app
  login: admin
- url: /(.*\.(css|js|jpg|png))$
  static_files: dest/\1
  upload: dest/.*\.(css|js|jpg|png)$
- url: /.*
  script: _go_app

skip_files:
- ^(.*/)?\.DS_Store$
- ^node_modules/(.*)
- ^gulpfile\.js$
- ^package\.json$
- ^src/(.*)
