runtime: go111

handlers:
- url: /api/location
  script: auto
  secure: always
- url: /api/location/(new|update|delete)
  script: auto
  login: admin
  secure: always
- url: /api/music
  script: auto
  secure: always
- url: /api/music/(new|update)
  script: auto
  login: admin
  secure: always
- url: /admin/(.*\.(png|js|css))$
  static_files: adminui/build/\1
  upload: adminui/build/.*\.(png|js|css)$
  login: admin
  secure: always
- url: /(.*\.(png|jpg|pdf|js|css))$
  static_files: ui/build/\1
  upload: ui/build/.*\.(png|jpg|pdf|js|css)$
  secure: always
- url: /admin$
  static_files: adminui/build/index.html
  upload: adminui/build/index.html
  login: admin
  secure: always
- url: /resume$
  script: auto
  secure: always
- url: .*
  static_files: ui/build/index.html
  upload: ui/build/index.html
  secure: always
