application: website
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  script: _go_app
- url: /(.*\.(css|js|jpg|png))$
  static_files: dest/\1
  upload: dest/.*\.(css|js|jpg|png)$

skip_files:
- ^(.*/)?\.DS_Store$
- ^node_modules/(.*)
- ^gulpfile\.js$
- ^package\.json$
- ^src/(.*)
