application: gold-summer-11
version: 1
runtime: go
api_version: go1

handlers:
- url: /api/location/(new|update)
  script: _go_app
  login: admin
  secure: always
- url: /api/location
  script: _go_app
  secure: always
- url: /api/music/(new|update)
  script: _go_app
  login: admin
  secure: always
- url: /admin\.(js|css)$
  static_files: dest/admin.\1
  upload: dest/admin\.(css|js)$
  login: admin
  secure: always
- url: /(.*\.(css|js|jpg|png))$
  static_files: dest/\1
  upload: dest/.*\.(css|js|jpg|png)$
  secure: always
- url: /admin
  script: _go_app
  login: admin
  secure: always
- url: /.well-known/acme-challenge/.*
  script: _go_app
- url: /.*
  script: _go_app
  secure: always

skip_files:
- ^(.*/)?\.DS_Store$
- ^node_modules/(.*)
- ^gulpfile\.js$
- ^package\.json$
- ^src/(.*)
- ^.git/(.*)
