runtime: go
version: 1
api_version: go1

handlers:
- url: /api/location
  script: _go_app
  secure: always
- url: /api/location/(new|update|delete)
  script: _go_app
  login: admin
  secure: always
- url: /api/music
  script: _go_app
  secure: always
- url: /api/music/(new|update)
  script: _go_app
  login: admin
  secure: always
- url: /.well-known/acme-challenge
  static_dir: .well-known/acme-challenge
  mime_type: text/plain
- url: /admin/(.*\.(png|js|css))$
  static_files: adminui/build/\1
  upload: adminui/build/.*\.(png|js|css)$
  login: admin
  secure: always
- url: /(.*\.(png|jpg|pdf|js|css))$
  static_files: ui/build/\1
  upload: ui/build/.*\.(png|jpg|pdf|js|css)$
  secure: always
- url: /admin$
  static_files: adminui/build/index.html
  upload: adminui/build/index.html
  login: admin
  secure: always
- url: /resume$
  script: _go_app
  secure: always
- url: .*
  static_files: ui/build/index.html
  upload: ui/build/index.html
  secure: always

skip_files:
- ^(.*/)?\.DS_Store$
- ^letsencrypt/(.*)
- ^.git/(.*)
- ^ui/node_modules
- ^ui/package.json
- ^ui/src
- ^ui/public
- ^adminui/node_modules
- ^adminui/package.json
- ^adminui/src
- ^adminui/public
