application: gold-summer-11
version: 1
runtime: go
api_version: go1

handlers:
- url: /api/location/(new|update)
  script: _go_app
  login: admin
- url: /api/location
  script: _go_app
- url: /api/music/(new|update)
  script: _go_app
  login: admin
- url: /admin\.(js|css)$
  static_files: dest/admin.\1
  upload: dest/admin\.(css|js)$
  login: admin
- url: /(.*\.(css|js|jpg|png))$
  static_files: dest/\1
  upload: dest/.*\.(css|js|jpg|png)$
- url: /admin
  script: _go_app
  login: admin
- url: /.*
  script: _go_app

skip_files:
- ^(.*/)?\.DS_Store$
- ^node_modules/(.*)
- ^gulpfile\.js$
- ^package\.json$
- ^src/(.*)
