runtime: go
api_version: go1

handlers:
- url: /api/location/(new|update)
  script: _go_app
  login: admin
  secure: always
- url: /api/location
  script: _go_app
  secure: always
- url: /api/music/(new|update)
  script: _go_app
  login: admin
  secure: always
- url: /.well-known/acme-challenge
  static_dir: .well-known/acme-challenge
  mime_type: text/plain

skip_files:
- ^(.*/)?\.DS_Store$
- ^node_modules/(.*)
- ^letsencrypt/(.*)
- ^gulpfile\.js$
- ^package\.json$
- ^src/(.*)
- ^.git/(.*)
